version: '3.8'

services:
  app:
    image: digitalapp:0.0.1
    ports:
      - "2005:2005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/project?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Swaroop@1157
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Swaroop@1157
      MYSQL_DATABASE: project
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
